// put all types here

export const GET_CURRENT_PROFILE_SUCCESS = "GET_CURRENT_PROFILE_SUCCESS";
export const GET_CURRENT_PROFILE_ERROR = "GET_CURRENT_PROFILE_ERROR";
export const PUT_CURRENT_PROFILE = "PUT_CURRENT_PROFILE";
